### ISSUE TITLE
NiFi node type does not use port property

### ISSUE THREAD

**Issue by kmlTE** [RADON-SODALITE/hybrid-compute-profile#4]
# Current behavior
[NiFi node type](https://github.com/RADON-SODALITE/radon-particles/blob/master/nodetypes/radon.nodes.nifi/Nifi/NodeType.tosca) contains property *port*, which is not used in the Standard interface operations and does not actually set a port for a NiFi instance.

# Expected behavior
[NiFi node type](https://github.com/RADON-SODALITE/radon-particles/blob/master/nodetypes/radon.nodes.nifi/Nifi/NodeType.tosca) should set the port for a NiFi instance.

**Comment by miwurster** [comment]
I think this will be fixed by pulling the latest `radon-h2020/radon-particles:master`, right @pjakovits?

**Comment by pjakovits** [comment]
Yes, it has now been fixed in the upstream: radon-h2020/radon-particles:master

The main repository now has the updates that enable:
- Deploying NiFi on ubuntu VMs
- Enable/disable access to web interface
- Change the NiFi port from 8080 to something else

NB! It does not yet fix  #5 for the newer NiFi GridFTP node types, but it does fix it for all the other ones. 
I will make a separate pull request for the GridFTP node types
